version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/data:/data/db

  #redis容器 - Redis container
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      # 数据文件 - data files
      - ./data/redis/data:/data:rw
    command: "redis-server --appendonly yes --port 6379"
    privileged: true
    restart: always
    networks:
      - bigworld_net
networks:
  bigworld_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16