version: '3.8'

services:
  #redis容器 - Redis container
  redis-master:
    image: redis:6.2.5
    container_name: redis-master
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./env_config/redis/master/redis.conf:/usr/local/etc/redis/redis.conf
      - ./env_config/redis/master/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "6379:6379"
      - "26379:26379" # Sentinel port
    networks:
      bigworld_net:
        ipv4_address: 172.20.0.2

  redis-slave1:
    image: redis:6.2.5
    container_name: redis-slave1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./env_config/redis/slave1/redis.conf:/usr/local/etc/redis/redis.conf
      - ./env_config/redis/slave1/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
      - "26380:26379" # Sentinel port
    networks:
      bigworld_net:
        ipv4_address: 172.20.0.3

  redis-slave2:
    image: redis:6.2.5
    container_name: redis-slave2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./env_config/redis/slave2/redis.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
      - "26381:26379" # Sentinel port
    networks:
      bigworld_net:
        ipv4_address: 172.20.0.4

networks:
  bigworld_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16